name: MLflow Tracking with DagsHub

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  track-and-train:
    runs-on: ubuntu-latest

    env:
      DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
      MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_PAT }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_PAT }}
      MLFLOW_TRACKING_URI: https://dagshub.com/Saiful0044/tweetmotions.mlflow

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run MLflow training script
      run: |
        python src/model/model_evaluation.py
